language: node_js
node_js:
- "8.2.1"

install:
- npm install newman

before_script:
- node --version
- npm --version
- newman --version

script:
- newman run PayAsYouGo.postman_collection.json -e AsYouGo.postman_environment.json
